// flow-typed signature: 9b8a790e9a675a506258085e000ea789
// flow-typed version: <<STUB>>/electron-settings_vgithub:jcrygier/electron-settings/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-settings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-settings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-settings/lib/observer' {
  declare module.exports: any;
}

declare module 'electron-settings/lib/settings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-settings/index' {
  declare module.exports: $Exports<'electron-settings'>;
}
declare module 'electron-settings/index.js' {
  declare module.exports: $Exports<'electron-settings'>;
}
declare module 'electron-settings/lib/observer.js' {
  declare module.exports: $Exports<'electron-settings/lib/observer'>;
}
declare module 'electron-settings/lib/settings.js' {
  declare module.exports: $Exports<'electron-settings/lib/settings'>;
}
