// flow-typed signature: a56651921fb7f8694ebc12c36bd6c99e
// flow-typed version: <<STUB>>/javascript-state-machine_v^2.4.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-state-machine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'javascript-state-machine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'javascript-state-machine/demo/demo' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/state-machine' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/state-machine.min' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/test/qunit/qunit' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/test/requirejs/require' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/test/runner' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/test/test_advanced' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/test/test_async' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/test/test_basics' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/test/test_classes' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/test/test_initialize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'javascript-state-machine/demo/demo.js' {
  declare module.exports: $Exports<'javascript-state-machine/demo/demo'>;
}
declare module 'javascript-state-machine/state-machine.js' {
  declare module.exports: $Exports<'javascript-state-machine/state-machine'>;
}
declare module 'javascript-state-machine/state-machine.min.js' {
  declare module.exports: $Exports<'javascript-state-machine/state-machine.min'>;
}
declare module 'javascript-state-machine/test/qunit/qunit.js' {
  declare module.exports: $Exports<'javascript-state-machine/test/qunit/qunit'>;
}
declare module 'javascript-state-machine/test/requirejs/require.js' {
  declare module.exports: $Exports<'javascript-state-machine/test/requirejs/require'>;
}
declare module 'javascript-state-machine/test/runner.js' {
  declare module.exports: $Exports<'javascript-state-machine/test/runner'>;
}
declare module 'javascript-state-machine/test/test_advanced.js' {
  declare module.exports: $Exports<'javascript-state-machine/test/test_advanced'>;
}
declare module 'javascript-state-machine/test/test_async.js' {
  declare module.exports: $Exports<'javascript-state-machine/test/test_async'>;
}
declare module 'javascript-state-machine/test/test_basics.js' {
  declare module.exports: $Exports<'javascript-state-machine/test/test_basics'>;
}
declare module 'javascript-state-machine/test/test_classes.js' {
  declare module.exports: $Exports<'javascript-state-machine/test/test_classes'>;
}
declare module 'javascript-state-machine/test/test_initialize.js' {
  declare module.exports: $Exports<'javascript-state-machine/test/test_initialize'>;
}
