// flow-typed signature: ecd5c2eb78f822012e0219b506ab7141
// flow-typed version: <<STUB>>/selectn_v^1.1.2/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'selectn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'selectn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'selectn/selectn' {
  declare module.exports: any;
}

declare module 'selectn/selectn.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'selectn/index' {
  declare module.exports: $Exports<'selectn'>;
}
declare module 'selectn/index.js' {
  declare module.exports: $Exports<'selectn'>;
}
declare module 'selectn/selectn.js' {
  declare module.exports: $Exports<'selectn/selectn'>;
}
declare module 'selectn/selectn.min.js' {
  declare module.exports: $Exports<'selectn/selectn.min'>;
}
